### ISSUE TITLE
验证码加载不出来

### ISSUE THREAD

**Issue by 1102731636** [ledccn/iyuuplus-dev#1]
![image](https://github.com/ledccn/iyuuplus-dev/assets/86068165/f5816ea7-f372-4107-896e-ea4eb9917928)

新标签页打开图片显示如下信息
Error: Call to undefined function Webman\Captcha\imagecreatetruecolor() in C:\iyuuplus-dev-master\vendor\webman\captcha\src\CaptchaBuilder.php:430
Stack trace:
#0 C:\iyuuplus-dev-master\plugin\admin\app\controller\AccountController.php(199): Webman\Captcha\CaptchaBuilder->build(120)
#1 C:\iyuuplus-dev-master\vendor\workerman\webman-framework\src\App.php(319): plugin\admin\app\controller\AccountController->captcha(Object(support\Request), 'login')
#2 C:\iyuuplus-dev-master\vendor\workerman\webman-framework\src\App.php(351): Webman\App::Webman\{closure}(Object(support\Request), 'login')
#3 C:\iyuuplus-dev-master\app\middleware\Install.php(28): Webman\App::Webman\{closure}(Object(support\Request))
#4 C:\iyuuplus-dev-master\vendor\workerman\webman-framework\src\App.php(341): app\middleware\Install->process(Object(support\Request), Object(Closure))
#5 C:\iyuuplus-dev-master\plugin\admin\app\middleware\AccessControl.php(47): Webman\App::Webman\{closure}(Object(support\Request))
#6 C:\iyuuplus-dev-master\vendor\workerman\webman-framework\src\App.php(341): plugin\admin\app\middleware\AccessControl->process(Object(support\Request), Object(Closure))
#7 C:\iyuuplus-dev-master\app\middleware\Install.php(28): Webman\App::Webman\{closure}(Object(support\Request))
#8 C:\iyuuplus-dev-master\vendor\workerman\webman-framework\src\App.php(341): app\middleware\Install->process(Object(support\Request), Object(Closure))
#9 C:\iyuuplus-dev-master\vendor\workerman\webman-framework\src\App.php(141): Webman\App::Webman\{closure}(Object(support\Request))
#10 C:\iyuuplus-dev-master\vendor\workerman\workerman\Connection\TcpConnection.php(646): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#11 C:\iyuuplus-dev-master\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #429)
#12 C:\iyuuplus-dev-master\vendor\workerman\workerman\Worker.php(1488): Workerman\Events\Select->loop()
#13 C:\iyuuplus-dev-master\vendor\workerman\workerman\Worker.php(1405): Workerman\Worker::forkWorkersForWindows()
#14 C:\iyuuplus-dev-master\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()
#15 C:\iyuuplus-dev-master\vendor\workerman\webman-framework\src\support\App.php(131): Workerman\Worker::runAll()
#16 C:\iyuuplus-dev-master\start.php(4): support\App::run()
#17 {main}

**Comment by 1102731636** [comment]
php.ini文件中;extension=gd的前置;没删除

**Comment by ledccn** [comment]
[php.zip](https://github.com/ledccn/iyuuplus-dev/files/14993808/php.zip)
官网下载的PHP 8.3程序，可使用此php.ini文件。
