### ISSUE TITLE
获取最新站点信息，同步站点列表失败

### ISSUE THREAD

**Issue by 663D74N** [ledccn/iyuuplus-dev#103]
![2024-09-20_111433](https://github.com/user-attachments/assets/6abcbf21-8f57-415c-9846-775de87692cb)

![2024-09-18_172239](https://github.com/user-attachments/assets/0cc5ca11-2ec5-409d-ab4a-577dfb21bf90)

![2024-09-18_172359](https://github.com/user-attachments/assets/4520a97d-cd7d-4439-b895-57351ee3096a)

iyuuplus-dev-8.2.39 及 iyuuplus-dev-8.2.40 试过一样错误
提示同步成功实际没有成功

**Comment by IFallowed** [comment]
同样遇到此问题，版本:iyuuplus-dev-8.2.4
![2024-10-08_214758](https://github.com/user-attachments/assets/e617677b-78ec-4e44-a750-d23eac5b74ba)
0

**Comment by kokgmx** [comment]
同问题，套件版和docker版本都有这个问题

**Comment by 907739769** [comment]
一样的问题 最终解决了吗

**Comment by ledccn** [comment]
重启容器后，代码仍旧未更新到最新版的；表示本地的git仓库损坏啦；需要进入docker容器的终端，执行下列命令即可

rm -rf /iyuu/.git/index.lock && cd /iyuu && git pull && php start.php stop

**Comment by Hoidcrazy** [comment]
> 重启容器后，代码仍旧未更新到最新版的；表示本地的git仓库损坏啦；需要进入docker容器的终端，执行下列命令即可
> 
> rm -rf /iyuu/.git/index.lock && cd /iyuu && git pull && php start.php stop

8.3.23版本也遇到了这个问题，用这个方式后并未解决
