### ISSUE TITLE
安装最新版镜像后data文件夹里没有自动创建数据库文件

### ISSUE THREAD

**Issue by CleverMod** [ledccn/iyuuplus-dev#109]
然后第一步设置数据库信息就一直报这个错误
![微信截图_20241001165906](https://github.com/user-attachments/assets/b2699668-5c26-4cd3-b4ca-59ea0873f744)

**Comment by CleverMod** [comment]
services:
  iyuuplus:
    image: iyuucn/iyuuplus-dev:latest
    container_name: iyuuplus
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "12312:8780/tcp"
    volumes:
      - /volume5/6T/Downloads:/6Downloads
      - /volume4/512G/DockerConfig/iyuu3/data:/data
      - /volume4/512G/DockerConfig/iyuu3/iyuu:/iyuu
      - /volume4/512G/DockerConfig/qb_upload/data/BT_backup:/qbUploadBackup
    environment:
      PUID: "0"
      PUID: "0"

**Comment by wang-potato** [comment]
同问，我今天重装也报这个错，请问你解决了吗

**Comment by WUDDC** [comment]
两位如果是群晖的话请把配置目录指向“/docker”目录下的目录中，例如创建“/docker/iyuu/data”和“/docker/iyuu/iyuu"并且将/data和/iyuu指向它们就可以了

**Comment by darklandy** [comment]
我也是这个问题 我解决了 把文件夹赋权就可以了 用everyone权限
