### ISSUE TITLE
猫站辅种显示成功，实际失败，似乎是种子识别错误

### ISSUE THREAD

**Issue by SilenQ** [ledccn/iyuuplus-dev#11]
猫站pter | 144309 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 116887 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 436119 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 255607 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 447888 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 466971 | 失败 | 请求错误：error_message为空 密钥或凭据过期
猫站pter | 13830 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 91891 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 300287 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 164311 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 447169 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 6499 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 414531 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 144266 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 9039 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 281857 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 408556 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 391242 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 8977 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 473269 | 失败 | 请求错误：error_message为空 密钥或凭据过期
猫站pter | 266646 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 187044 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 20969 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 174646 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 405101 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 28791 | 成功 | {"arguments":{},"result":"unrecognized info"}
猫站pter | 290774 | 失败 | HTTP/1.1 415 Unsupported Media Type
猫站pter | 481156 | 失败 | 请求错误：error_message为空 密钥或凭据过期

**Comment by SilenQ** [comment]
目前TR做种的都是这个问题，QB有能正常成功辅种的

**Comment by ledccn** [comment]
应该是触发流量控制了；我程序内也做一下检查。

**Comment by SilenQ** [comment]
> 应该是触发流量控制了；我程序内也做一下检查。
我查了一下这里面的每一个种子ID，在猫站里都是不存在的
