### ISSUE TITLE
能否实现下载器下载完成种子后自动进行转移

### ISSUE THREAD

**Issue by smomop** [ledccn/iyuuplus-dev#113]
目前好像没发现下载器下载完成种子后进行自动转移的配置选项，只有具体的时间进行转移，还是说我没找对地方🤔。
痛点：目前使用TR做种，但是下载不想用TR，想使用QB来下载

**Comment by IFallowed** [comment]
TR不是有保存目录和临时目录吗，未下载完的在临时目录，下载完成后自动移动到保存目录（以上对QB也是同理）。你只配置IYUU转移数据保存目录不就行了吗

> 目前好像没发现下载器下载完成种子后进行自动转移的配置选项，只有具体的时间进行转移，还是说我没找对地方🤔。 痛点：目前使用TR做种，但是下载不想用TR，想使用QB来下载
