### ISSUE TITLE
iyuu 绑定icc2022 失败

### ISSUE THREAD

**Issue by 954708775** [ledccn/iyuuplus-dev#119]
IYUU站点绑定失败，错误信息：请求IYUU失败，状态码：801，返回信息：非法请求：非法请求：合作站点icc2022 校验失败

这个值应该是全对的，不知道哪里有的问题

**Comment by confstantine** [comment]
同样，返回信息是timeout

**Comment by tlze** [comment]
可以了，ICC公告已经修复（cf的SSL的锅）。

**Comment by 954708775** [comment]
> 可以了，ICC公告已经修复（cf的SSL的锅）。

好的，感谢修复，之前问到伟大大，说是要布署下什么线路

**Comment by Ercndye** [comment]
现在又出现了这个情况，大佬怎么搞
