### ISSUE TITLE
任务日志的长连接端口也需要修改一下，跟随手动设置。

### ISSUE THREAD

**Issue by AisukaYuki** [ledccn/iyuuplus-dev#12]
如题：
https://github.com/ledccn/iyuuplus-dev/blob/c56b39867407afd4dd0d3a29419d738f2d356ae5/plugin/cron/app/admin/view/crontab/screen.html#L23

#13

**Comment by devome** [comment]
要不你直接pr一下？

**Comment by AisukaYuki** [comment]
> 要不你直接pr一下？

已经PR了呢

**Comment by devome** [comment]
啊，不好意思，没注意到
