### ISSUE TITLE
请求合作站点失败：Failed to connect to chdbits.co port 443: Connection refused

### ISSUE THREAD

**Issue by AppleFrank** [ledccn/iyuuplus-dev#121]
chdbits 连不上

**Comment by muzi-xiaoren** [comment]
![屏幕截图 2024-11-03 233706](https://github.com/user-attachments/assets/288e933b-0d86-43fb-9079-10a037cd694d)
![屏幕截图 2024-11-03 233717](https://github.com/user-attachments/assets/c28159f7-2056-47ee-8268-2af9b3c153f6)

**Comment by AppleFrank** [comment]
就是如果你想绑定chd作为合作站点的话会连接不上

**Comment by ledccn** [comment]
本周会在IYUU服务器增加代理通道，解决此问题。
