### ISSUE TITLE
同步站点列表失败：Failed to connect to dev.iyuu.cn port 443 after 3 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by wayhome000** [ledccn/iyuuplus-dev#123]
webui界面报错，无法同步站点，也无法辅种

**Comment by kurokasei01** [comment]
![photo_2024-11-08_00-08-41](https://github.com/user-attachments/assets/3ca80b65-8211-41f2-82b0-d6c08142330f)
8.2.48了还是失败

**Comment by wayhome000** [comment]
> ![photo_2024-11-08_00-08-41](https://private-user-images.githubusercontent.com/151392936/384042986-3ca80b65-8211-41f2-82b0-d6c08142330f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMjg3MzUsIm5iZiI6MTczMTAyODQzNSwicGF0aCI6Ii8xNTEzOTI5MzYvMzg0MDQyOTg2LTNjYTgwYjY1LTgyMTEtNDFmMi04MmIwLWQ2YzA4MTQyMzMwZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMTEzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDFlN2Q3Y2I1MzNiNTEwY2IyYTljNmEyMWZlZTNhMjMyY2QwOWYwNDBmMGFiNTJhZTBjMWZlZGYxZDQ1ZGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aNNICK9EBxW6tzjkgVp-wCCiwXpdEYydih7MOHTDi30) 8.2.48了还是失败

一样的，能更新，但更新后还是一样。我尝试删除docker重装，结果出现了新的问题，现在连初始化都过不去了。

**Comment by tin607** [comment]
同样的问题。无法辅种。

**Comment by Ganya-A** [comment]
一样，从11月开始，站点都辅不了了

**Comment by Hyphen-H** [comment]
+1

**Comment by ledccn** [comment]
重启容器后，代码仍旧未更新到最新版的；表示本地的git仓库损坏啦；需要进入docker容器的终端，执行下列命令即可

rm -rf /iyuu/.git/index.lock && cd /iyuu && git pull && php start.php stop
