### ISSUE TITLE
辅种提示1.准备下载种子 Driver [ptlgs] not supported.

### ISSUE THREAD

**Issue by UniqueXXL** [ledccn/iyuuplus-dev#125]
辅种：1.准备下载种子 Driver [ptlgs] not supported.柠檬、雨都显示这个

**Comment by 879611427** [comment]
我的也是,站点劳改所

**Comment by 879611427** [comment]
> 我的也是,站点劳改所

iyuu是最新的

**Comment by 879611427** [comment]
> 辅种：1.准备下载种子 Driver [ptlgs] not supported.柠檬、雨都显示这个

更新到最新版

**Comment by 879611427** [comment]
一样的问题，更新到最新版了8.2.55，站点劳改所

**Comment by UniqueXXL** [comment]
重启容器，填passkey。。。就行了

**Comment by 879611427** [comment]
> 重启容器，填passkey。。。就行了

我的是没有获取最新站点

**Comment by UniqueXXL** [comment]
刷新站点也没用吗

**Comment by ledccn** [comment]
重启容器后，代码仍旧未更新到最新版的；表示本地的git仓库损坏啦；需要进入docker容器的终端，执行下列命令即可

rm -rf /iyuu/.git/index.lock && cd /iyuu && git pull && php start.php stop
