### ISSUE TITLE
极空间docker，辅种失败：Could not resolve host: dev.iyuu.cn

### ISSUE THREAD

**Issue by hzqyihui** [ledccn/iyuuplus-dev#130]
部署上自动辅种很久了，一直都是没问题的， 但是前段时间把任务停了，前两天又打开任务，发现辅不上了，看打印日志，提示：
Could not resolve host: dev.iyuu.cn ， 就结束了。 请问这是什么原因，看起来是解析不了域名， 我已经更新了最新的包，配置用的还是原来的， 仍有问题。求解！

**Comment by ledccn** [comment]
更新可能会失败，建议去容器内，执行：
`cd /iyuu && git pull`，如果仍有问题，可进群提问。

**Comment by songdone** [comment]
同问，没法辅种，Could not resolve host: dev.iyuu.cn
