### ISSUE TITLE
公众号和网站无法访问，无法获取 token

### ISSUE THREAD

**Issue by QAQrz** [ledccn/iyuuplus-dev#132]
https://iyuu.cn/ 和公众号都无法访问
![image](https://github.com/user-attachments/assets/17adb0c3-ffdc-4897-b39d-954550c5c340)
![image](https://github.com/user-attachments/assets/b099fc8d-0fde-4e7e-901d-d5ed5b0158a8)

**Comment by ledccn** [comment]
阿里云工程师回复说：触发了oom（out of memory）
已授权阿里云工程师，正在修复、排查

**Comment by ledccn** [comment]
已修复
