### ISSUE TITLE
使用自动辅种，transmission显示待辅种，却没有发送到tr中

### ISSUE THREAD

**Issue by LastNever** [ledccn/iyuuplus-dev#136]
之前使用qt没问题，后面由于刷流会自动删种（但没删除辅种种子）导致重复下载，于是启用了主辅分离，主用qt，辅种只用tr
改为wr后，只有第一次能成功，后面就显示待辅种。昨天清除种子缓存后也是第一次成功了，后面就一直显示待辅种，今天看还是有问题，前来请教
![image](https://github.com/user-attachments/assets/895e5997-fb32-4402-a3c7-4b6123ee103d)

**Comment by ledccn** [comment]
为保障账号安全，部分站点有每日下载种子数的限制。
带辅助的种子会在未来N天内全部辅种完毕。
如果您确信没问题，可以编辑站点配置，把每日辅种数限制 字段，改为0（不限制）
