### ISSUE TITLE
自动辅种周期任务失效，但手动触发则有效

### ISSUE THREAD

**Issue by TimeEternal** [ledccn/iyuuplus-dev#142]
docker容器 latest
如题目描述配置了每6小时自动转移并辅种
看日志 是在周期执行的
<img width="1534" alt="338a0de5f076268f4c617094e188e89" src="https://github.com/user-attachments/assets/c62b0d4e-93d6-41c0-a254-d07e964f730d">
但是 实际上 没有任何的种子被辅上， 且微信没有任何的通知
但当我手动触发后，就会直接全部辅种成功
<img width="1293" alt="548ac6aa747c8b49c37fc5b9b115cbd" src="https://github.com/user-attachments/assets/9095693f-c88f-4ee0-abb9-2c29f535eae5">
这里有明确的时间分割， 两次均是我手动触发才辅种上的。

很奇怪，不知道为什么，求解答。

**Comment by ledccn** [comment]
错峰辅种就可以；应该是您设置的定时时间执行时，服务器忙碌，请求失败。
