### ISSUE TITLE
群辉全新安装dev版docker，mysql一直报错

### ISSUE THREAD

**Issue by naoki66** [ledccn/iyuuplus-dev#147]
docker环境：
version: '3.8'

services:
  iyuuplus:
    image: iyuucn/iyuuplus-dev:latest
    container_name: iyuu-dev
    network_mode: bridge
    restart: always
    environment:  
     - TZ=Asia/Shanghai
    volumes:
      - /volume1/DockerConfig/iyuuplusdev/iyuu:/iyuu
      - /volume1/DockerConfig/iyuuplusdev/data:/data
    ports:
      - "8780:8780"
------------其中
DockerConfig/iyuuplusdev文件夹为新建，给了权限
![image](https://github.com/user-attachments/assets/0b7ac38b-b864-411f-987b-a59cb066428c)

启动后报错
[iyuu-dev-20241220122910.log](https://github.com/user-attachments/files/18207158/iyuu-dev-20241220122910.log)

**Comment by naoki66** [comment]
尝试给容器root权限
    environment:
      - PUID=0
      - PGID=0
似乎并不生效

**Comment by vinootian** [comment]
我进去看了，mysqld文件夹是空的

**Comment by naoki66** [comment]
Installing MariaDB/MySQL system tables in '/data' ...
2024-12-20 12:26:22 0 [ERROR] mariadbd: Can't create/write to file './ddl_recovery.log' (Errcode: 13 "Permission denied")
2024-12-20 12:26:22 0 [ERROR] DDL_LOG: Failed to create ddl log file: ./ddl_recovery.log
2024-12-20 12:26:22 0 [ERROR] Aborting


经过检查，似乎启动后，会把文件夹拥有者权限给到 不知名账号102导致错误
强制停止后，把文件夹权限添加 everyone后恢复

**Comment by peterroe** [comment]
还真是，遇到同样的问题 :)

**Comment by naoki66** [comment]
这个应该是docker镜像某个程序对 /data 目录进行赋权 102 导致失效

**Comment by UltramarineSky** [comment]
> 这个应该是docker镜像某个程序对 /data 目录进行赋权 102 导致失效

不知道怎么解决好，威联通上ssh停止后手动改权限还是没好，一启动就自动改成`102/103`了
