### ISSUE TITLE
无法辅种，Could not resolve host: dev.iyuu.cn

### ISSUE THREAD

**Issue by Hotwill** [ledccn/iyuuplus-dev#151]
最近这几天辅种时报错，Could not resolve host: dev.iyuu.cn，请问是什么原因？

2024-12-28 16:37:44即将执行自动辅种，任务id：1
 
Could not resolve host: dev.iyuu.cn
 
 当前时间：2024-12-28 16:37:46
 IYUU版本：8.2.56
 Docker：是
 操作系统：Linux
 运行环境：Linux
 PHP二进制路径：/usr/bin/php83
 PHP版本号：8.3.14
辅种完毕，感谢使用IYUU自动辅种！

**Comment by ledccn** [comment]
更新版本

**Comment by Hotwill** [comment]
已经更新到最新版了，还是不行，报同样的错误

2024-12-29 14:58:37即将执行自动辅种，任务id：1
 
Could not resolve host: dev.iyuu.cn
 当前时间：2024-12-29 14:58:39
 IYUU版本：8.2.57
 Docker：是
 操作系统：Linux
 运行环境：Linux
 PHP二进制路径：/usr/bin/php83
 PHP版本号：8.3.15
辅种完毕，感谢使用IYUU自动辅种！

**Comment by Hotwill** [comment]
进入容器，执行`cd /iyuu && git pull`后恢复正常
