### ISSUE TITLE
设置数据库那里数据库名、用户名和密码都是iyuu吗？

### ISSUE THREAD

**Issue by tsg1981gmail** [ledccn/iyuuplus-dev#16]
设置数据库那里数据库名、用户名和密码都是iyuu吗？

**Comment by tsg1981gmail** [comment]
现在一直卡在这里，用docker部署的。

**Comment by Orange-Summer** [comment]
这个好像默认的直接继续就行了？我记得我没修改

**Comment by maodou6** [comment]
我也遇到了，请问解决了吗

**Comment by ledccn** [comment]
挂载目录的应拥有读写权限。否则可能导致内置的mysql启动失败。

**Comment by ghalong** [comment]
请问这个问题解决了吗？我看没有显示已解决的信息，为什么关了呢，我是群晖7.0，今天刚拉的最新代码，也有这个问题，目录都是具有读写权限，也尝试过高权限运行，但是启动之后一直报上面@naoki66那样的错误，打开web页面尝试登录，就会报截图中的错误
<img width="1078" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/9bd56968-ca74-459b-a052-de5b5f0751bb">
点进配置的IYUU目录，iyuu目录下有很多数据，但是data目录却是空的。还请开发大佬们帮忙定位一下问题，感谢三连
