### ISSUE TITLE
[建议] 自动将辅种种子的子文件夹名修改为初始种子的子文件夹名

### ISSUE THREAD

**Issue by LegendAdmin** [ledccn/iyuuplus-dev#19]
有时会遇到种子内容一样但文件名不一样的情况
这时子文件夹名也不一样
就会导致无法自动辅种
需要修改初始种子（或者辅种种子）的子文件夹名
如图所示
![PixPin_2024-05-03_14-57-09](https://github.com/ledccn/iyuuplus-dev/assets/29401874/b3c0a1c2-98eb-4ef9-975d-a272b308f6a2)

**Comment by ledccn** [comment]
目前需求较多，等后面有时间再搞。
