### ISSUE TITLE
绑定下载器提示我用户名不能为空以及绑定ICC2022 站点错误

### ISSUE THREAD

**Issue by tiger0012** [ledccn/iyuuplus-dev#23]
我确定我输入的用户名没有空格，以及passkey与uid都没错,也换过浏览器。
如图：
<img width="440" alt="12223333" src="https://github.com/ledccn/iyuuplus-dev/assets/52605575/6760beb7-db71-40ec-949c-793738cb5ace">
<img width="377" alt="23333" src="https://github.com/ledccn/iyuuplus-dev/assets/52605575/478c2f75-835d-4742-9e90-26b922b8ebdb">

**Comment by ledccn** [comment]
已修复。
