### ISSUE TITLE
有几个问题：辅种提示不是一个有效的 torrent 文件

### ISSUE THREAD

**Issue by fanhengyuan** [ledccn/iyuuplus-dev#28]
作者你好，我看馒头辅种成功了。
但猫站有这个错误提示：
异常信息：4.调度事件，种子发送给下载器之前 HTTP/1.1 415 Unsupported Media Type
string(69) "错误：'1715052534.torrent' 不是一个有效的 torrent 文件。"
![20240507113931](https://github.com/ledccn/iyuuplus-dev/assets/16678140/b006888c-509e-4954-a753-64814825d14f)

问题2：辅助没有日志（为空）。 `/app/cron/admin/crontab/screen?crontab_id=1&task_type=10`  就是这个路径页面内容的为空，重启docker镜像也试过了。

项目是参考这个运行起来的： https://github.com/Tinywan/docker-php-webman

还有就是如果发现咱这个项目有Bug，可以提PR贡献吧。

**Comment by ledccn** [comment]
可以pr的，感谢使用和关注。

**Comment by ledccn** [comment]
猫站 辅种一定数量时，会导致限流；请求种子后返回的内容，IYUU没验证类型：html 或者 meteinfo
