### ISSUE TITLE
绑定合作站点icc2022,提示非法请求，合作站点校验失败。

### ISSUE THREAD

**Issue by fhawktuo** [ledccn/iyuuplus-dev#33]
![image](https://github.com/ledccn/iyuuplus-dev/assets/99779704/f8097158-44d8-4b18-8713-8e053f21431f)

**Comment by ledccn** [comment]
多试几次；可能是cf盾影响了。建议向站点反馈一下。

**Comment by alexyilinzhu** [comment]
和站点反馈过了 磁盘满了 现在可以了
