### ISSUE TITLE
docker 运行出错

### ISSUE THREAD

**Issue by FormatToday** [ledccn/iyuuplus-dev#34]
05/11 11:13 docker 镜像可能有问题，运行出错。
![image](https://github.com/ledccn/iyuuplus-dev/assets/20515769/81f7f656-fcc2-49a0-9249-c83cae8d674e)

**Comment by ledccn** [comment]
容器启动时拉取代码失败了。
可以停止容器，清空/iyuu 和 /data 目录内的数据，再启动容器。

**Comment by FormatToday** [comment]
好嘞，我试下发自我的 iPhone在 2024年5月11日，11:29，David ***@***.***> 写道：﻿
容器启动时拉取代码失败了。
可以停止容器，清空/iyuu 和 /data 目录内的数据，再启动容器。
