### ISSUE TITLE
iyuu-dev启动过程中连接数据库报错，导致无法登录IYUU

### ISSUE THREAD

**Issue by ghalong** [ledccn/iyuuplus-dev#36]
机器环境：群晖7.1
安装方式：docker
尝试过以高权限（root）运行本容器，依旧报相同的错误
映射的IYUU两个路径安装时已经设置为读写权限，如下图
<img width="575" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/f4c3c8c6-cef7-4f36-8610-77b36b722739">

由于日志导不出来，只好截图，报错信息如下，按时间降序排列的
<img width="1531" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/f2556151-6ec4-44b6-9907-179bf1756587">

<img width="1565" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/1036fe43-8b7d-4201-a019-fe5b6dda5380">

<img width="1491" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/ccf0d4ba-bdf0-41fa-ba2f-424fa0c1cb2a">

<img width="1464" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/b4651101-c026-4bce-9bc8-7b57051c8702">

<img width="1513" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/9ff36197-2b6f-4136-9f82-6203784c4ddf">

其中第一个报错信息出现在如下截图里，好像是写数据库时权限拒绝导致的，但是我不清楚这个被拒绝的目录是来自哪里的
<img width="1022" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/10e8f7ab-6428-4a3b-a5ec-aeda4ad94004">

这时去尝试登录，会示这个错误
![image](https://github.com/ledccn/iyuuplus-dev/assets/6925193/d04eb37c-faac-467f-b364-f18de19bc55c)
经过查看映射的iyuu目录以及data目录，发现iyuu里面有很多数据，但是data目录下是空的

另外发现一个现象，映射的data目录的拥有者是102，而iyuu的拥有者是登录账号自身。尝试关闭IYUU后修改data目录的拥有者为登录账号后，重新运行IYUU，发现data目录的拥有者又变成102了，而且IYUU启动中依旧报上面的数据库错误。

辛苦大佬百忙中抽空看一下这个问题，谢谢

**Comment by ledccn** [comment]
sudo docker run -itd \
    -p 8780:8780 \
    --name IYUUPlus \
    --restart=always \
    iyuucn/iyuuplus-dev:latest
    
你可以试试，不挂载直接安装，看是否还报错。一般是权限问题引起的。

**Comment by ledccn** [comment]
你的报错日志里面已经提示，没权限了。

**Comment by ghalong** [comment]
> 你的报错日志里面已经提示，没权限了。

感谢大佬回复，我把data的映射删除后，就一切正常了。只不过这样的话将来想备份数据库的话是不是会麻烦一点，我一会儿尝试把data目录的访问权限改为全部再试试。再有就是iyuu目录跟data目录都是通过相同方式指定的，为什么只有data目录会出现权限问题呢，而且data目录的所有者还变来变去的，感觉很奇怪

**Comment by ledccn** [comment]
回头我问问懂docker的大佬，来解决这个问题。我对docker不了解。

**Comment by ghalong** [comment]
> 回头我问问懂docker的大佬，来解决这个问题。我对docker不了解。

好的，这是我见过的处理issue问题最快的代码仓库，大佬真是太给力了，这个问题就先关了

**Comment by devome** [comment]
你检查下这里的权限对不对

![image](https://github.com/ledccn/iyuuplus-dev/assets/93664269/1038d34a-08cd-4864-9b0d-5a94ec356639)

**Comment by ghalong** [comment]
再来追加一下上面提到的把data目录权限修改为所有人具有读写权限的尝试结果，先关闭iyuu docker，然后修改权限，保险起见，iyuu跟data目录全部清空，iyuu docker也删除（刚开始我没删除，启动后报了一堆错），然后重新安装iyuu，启动后，就一切正常了

**Comment by ghalong** [comment]
> 你检查下这里的权限对不对
> 
> ![image](https://private-user-images.githubusercontent.com/93664269/329762340-1038d34a-08cd-4864-9b0d-5a94ec356639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTIxMTAsIm5iZiI6MTcxNTQxMTgxMCwicGF0aCI6Ii85MzY2NDI2OS8zMjk3NjIzNDAtMTAzOGQzNGEtMDhjZC00ODY0LTliMGQtNWE5NGVjMzU2NjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA3MTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTE2NGUxNzYxZWM4ZmE5NDZlOGExNWEyMWY1ZjdiYTJiZmU5NWI0YzU2NTBjNjEyMjBiM2IzOTczY2Y5YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GIFZbrP7b7cm5sJBGqEQEEI8xfuZmGpsW1ZKCnylrs8)

这个检查过了，跟iyuu的映射目录的权限是一样的，iyuu目录权限没问题的话按理说这里的权限应该也没问题才对，但是iyuu容器一启动，这个data目录的所有者就变成了一个不知道哪来的102，应该就是这个问题导致了102不再具备访问data目录的权限了，我现在把data目录的访问权限改成所有人都具有读写权限后，启动后就不存在任何问题了

**Comment by devome** [comment]
102是容器内的数据库用户。

**Comment by ghalong** [comment]
关闭容器后，将data目录权限移除所有人，添加admin，结果又出现最开始的报错了，102应该是低权限用户吧
<img width="701" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/8d16ab0e-a60f-482b-9d9c-1e8ecf6abb06">

<img width="1017" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/5ca6a22d-461b-48d0-b26f-90efa181d788">

**Comment by devome** [comment]
要看“共享文件夹” /volume2/docker 的共享权限

**Comment by ghalong** [comment]
> 要看“共享文件夹” `/volume2/ssd` 的共享权限，仔细看我截图。
嗯  我看了一下  跟你截图里的好像也是一样的，而且当前登录群晖的账号也是有读写权限
<img width="903" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/6925193/1de539e5-78dd-4f46-b90d-5b13b271cc16">

**Comment by devome** [comment]
那就很奇怪了，搞不懂群晖奇奇怪怪的问题。

**Comment by ghalong** [comment]
> 那就很奇怪了，搞不懂群晖奇奇怪怪的问题。

我主力机其实是unraid，但是那个机器老是崩溃死机，一年多了也没整好，后来就放弃了，只好用这个群晖备用机 -_-

**Comment by UltramarineSky** [comment]
请问这个解决了吗？遇到了一样的问题
一直用的都是老版的iyuuplus，更新时堆栈里iyuuplus也更新成新版的iyuuplus-dev，设置时没注意进去后一直报长链接问题就把docker卸载了，后来看到是出了新版的，按照帮助文档的docker-compose改了后就一直报错
![截图_20240518070952](https://github.com/ledccn/iyuuplus-dev/assets/54146035/e76b28ab-893f-42d1-8b18-3518328209c0)
