### ISSUE TITLE
部分站点辅种报错，如馒头U2天雪等

### ISSUE THREAD

**Issue by TAN-Z-H** [ledccn/iyuuplus-dev#4]
馒头：请求错误：Could not resolve host: https
U2：Driver [dmhy] not supported.
天雪：Driver [skyeysnow] not supported.
你堡：请求错误：HTTP/2 404 
铂金家：请求错误：HTTP/2 404 
MDU：请求错误：HTTP/2 404 

站点配置均为20个，10s，未勾选https等选项

**Comment by ledccn** [comment]
HTTP/2 404：表示种子在站点已删除；
Driver [dmhy] not supported：表示当前站点咱未在新版适配。
