### ISSUE TITLE
为特定站点设置代理

### ISSUE THREAD

**Issue by MonRain** [ledccn/iyuuplus-dev#40]
某些站点因为网络环境无法访问导致辅种（下载种子文件）失败，设置全局代理又会影响大部分站点的访问和流量管控。
能否参照nastool，对特定站点设置代理访问。

**Comment by ledccn** [comment]
目前，代码里面隐含有这个功能，只是没有开放；我放出来吧。

**Comment by ledccn** [comment]
已实现
