### ISSUE TITLE
为什么更新后会经常辅一些本地没有的种子

### ISSUE THREAD

**Issue by KONNY-GitHub** [ledccn/iyuuplus-dev#42]
![屏幕截图 2024-05-16 104324](https://github.com/ledccn/iyuuplus-dev/assets/62805720/7bd03dac-bb60-4a2e-9733-863298bf66fe)

**Comment by ledccn** [comment]
辅种是有一套算法的，这套算法内为了适配各种可能性，比如重制种、改名称等，是会出来无关的种子（跟你本机已有的种子大小完全相等）。
你可以删除下载器内的辅种，下次就不会添加了。
