### ISSUE TITLE
一些站点辅种报错

### ISSUE THREAD

**Issue by lintiger86** [ledccn/iyuuplus-dev#43]
1.准备下载种子 请求错误：error_message为空 Cookie过期
4.调度事件，种子发送给下载器之前 HTTP/1.1 415 Unsupported Media Type
1.准备下载种子 请求错误：HTTP/2 401
1.准备下载种子 请求错误：HTTP/2 404

请教这些报错是什么意思，如何解决，谢谢。

**Comment by ledccn** [comment]
https://doc.iyuu.cn/guide/reseed-torrent
