### ISSUE TITLE
通知服务

### ISSUE THREAD

**Issue by a1257636709** [ledccn/iyuuplus-dev#44]
请求作者就快关于通知的研发  希望增加企业微信中 应用的通知  如下图 留出代理服务器添加接口  谢谢
![Uploading 1716001348842.png…]()

**Comment by a1257636709** [comment]
![1716001348842](https://github.com/ledccn/iyuuplus-dev/assets/96871333/07abb53c-1be4-48ba-ae48-41891028de9b)

**Comment by ledccn** [comment]
当前，暂无开发对接企业微信应用的想法；
主要原因是，搭建一个私有的通知服务，对大多数用户来说门框较高；
后续可以继续关注。

**Comment by a1257636709** [comment]
谢谢
