### ISSUE TITLE
一直刷屏报错“长链接断线，端口:8780”

### ISSUE THREAD

**Issue by gnailam** [ledccn/iyuuplus-dev#48]
![屏幕截图 2024-05-21 013308](https://github.com/ledccn/iyuuplus-dev/assets/132273883/c6a46bd4-2bb5-4cdd-815c-0292c9bdf8bb)

部署方式：unraid docker
部署类型：新建空目录全新安装
访问浏览器：chrome 125.0.6422.61 / edge 125.0.2535.51

另外dockerhub里旧版本镜像全删了吗？

**Comment by xqw8889** [comment]
请重新拉取新镜像安装
