### ISSUE TITLE
咨询下你们在群晖里使用不卡么。

### ISSUE THREAD

**Issue by 233cy** [ledccn/iyuuplus-dev#49]
<img width="2409" alt="图片" src="https://github.com/ledccn/iyuuplus-dev/assets/29916783/092ad4f1-06d2-43d9-ad00-6ca2255bad13">
为什么我群晖使用很卡，目前环境是在docker中使用的

**Comment by xqw8889** [comment]
说明你填的地址不对 访问超时 docker无法访问此地址

**Comment by ledccn** [comment]
不卡
