### ISSUE TITLE
套件版dev按设定安装设置后，执行辅种任务0成功

### ISSUE THREAD

**Issue by uzuki5245** [ledccn/iyuuplus-dev#50]
如题，在群晖的矿神套件中安装的qb，tr和iyuu dev，下载器设置，站点设置，辅种任务新建都没有报错，几个站点都已经添加了必要的passkey，cookie，token等等，但是任务执行状态一直为0成功。已经折腾了两小时了，查了很多教程，还是没弄明白是怎么回事。

![屏幕截图 2024-05-21 154115](https://github.com/ledccn/iyuuplus-dev/assets/104311342/b0833529-a379-476e-8bb8-4ae1cecd1a00)
![屏幕截图 2024-05-21 154146](https://github.com/ledccn/iyuuplus-dev/assets/104311342/7fee0a06-327b-4d8b-bb8a-6c6d5a0f56f1)

**Comment by uzuki5245** [comment]
在通用设置-系统设置-IYUU设置中填入token后，在管理中心-站点顺利绑定合作站点，然后解决该问题。
一开始还以为是在管理中心-通知渠道绑定iyuu的token，主要是跟着贴吧简易版攻略，没有第一时间申请token，绕了弯路。

**Comment by ledccn** [comment]
感谢分享安装经历。
