### ISSUE TITLE
支持下载器URL中hostname不为域名或ip

### ISSUE THREAD

**Issue by so1ve** [ledccn/iyuuplus-dev#51]
![](https://github.com/ledccn/iyuuplus-dev/assets/58381667/b7415542-0f8a-44b5-b720-6aba62626ca5)

docker中只要容器使用同一个网络的话，是可以通过容器名直接作为主机名来访问的

**Comment by cnRuanYF** [comment]
同求，一个月前还是可以直接用设备名作为hostname并正常工作的，最近更新之后想改配置，发现不能保存了，希望去掉这个限制

**Comment by ledccn** [comment]
v8.2.23+ 已放宽限制.

**Comment by deardeer7** [comment]
大家可以用域名了吗？我已更新8.2.23，尝试域名或者使用localhost+端口还是不行的
