### ISSUE TITLE
辅种站点重复

### ISSUE THREAD

**Issue by Othanse** [ledccn/iyuuplus-dev#61]
原种Tracker：
![image](https://github.com/ledccn/iyuuplus-dev/assets/11609128/f826b06d-9bf4-44cf-a4ee-80d944af30a0)

辅种后的Tracker：
![image](https://github.com/ledccn/iyuuplus-dev/assets/11609128/bf21c6b5-9916-473c-b504-f5355bb5b91a)

都是一个站点的

**Comment by ledccn** [comment]
问问站点的管理，为什么允许重复的种子；或者去站点搜索这个名字，看看是否确实有两个？
