### ISSUE TITLE
如何把一个下载器站点A的种子，辅种到站点B的同时放到另外一个下载器里

### ISSUE THREAD

**Issue by jiang925** [ledccn/iyuuplus-dev#62]
我现在有两个下载器。一个走VPN的qb1和一个不走VPN的qb2。有的站点用qb1下载，有的站点用qb2下载。

现状是iyuu会把qb1里站点A的种子，辅到站点B，然后放在qb1里面下载。我需要让站点B的辅种都放到qb2里面，即使原始种子来自于qb1。

**Comment by yohaoquan** [comment]
同求。原来辅种方法是将.torrent放在目标下载器监控文件夹来实现，但现在是直接向原种存在的下载器发送下载请求，没有指定目标下载器的能力。希望可以加入此功能。

**Comment by ledccn** [comment]
已实现此功能；创建辅种任务的时候，可选“主辅分离”。
