### ISSUE TITLE
可以在docker配置中增加一个禁用mysql或者更改端口的选项吗？

### ISSUE THREAD

**Issue by DoraTiger** [ledccn/iyuuplus-dev#63]
如题，部分网站仅支持v6访问并下载种子（如BYR），docker仅在host模式下可以访问v6（nas本身docker不提供v6），该模式下容器的mysql服务与nas本身Mariadb端口冲突了。

**Comment by ledccn** [comment]
后面会出一个不带mysql的docker镜像
