### ISSUE TITLE
一直报错：长链接断线

### ISSUE THREAD

**Issue by leonedit** [ledccn/iyuuplus-dev#64]
使用Luckey的Web服务进行子规则反代，按照"https://doc.iyuu.cn/guide/qa-iyuuplus#websocket_3131"和"https://doc.iyuu.cn/guide/qa-others#反向代理服务器进行的额外设置"这两处文档进行设置并刷新页面，还是提示长链接断线，端口：3131，请指正

**Comment by AisukaYuki** [comment]
3131只有docker安装是才有用，你自己源码安装的话。需要手动用[nginx反代](https://doc.iyuu.cn/guide/qa-iyuuplus#nginx_config)一次，再用lucky反代套证书。wiki中lucky的额外设置只是和websockt支持相关的。

**Comment by leonedit** [comment]
我用的是绿联Docker部署的方式，不是源码安装

**Comment by leonedit** [comment]
局域网访问是正常的，使用lucky的Web服务功能反代到https://域名:端口的方式，也加入了自定义配置，但使用反代后的域名访问就会提示长连接断线

**Comment by AisukaYuki** [comment]
iyuu网页，右上角点开wifi小图标，把长连接端口改为反代后的端口。而不是3131。

**Comment by leonedit** [comment]
如此就解决了，感谢指教

**Comment by ledccn** [comment]
https://doc.iyuu.cn/guide/qa-others#proxy
