### ISSUE TITLE
长链接断线；unraid docker部署；使用Nginx Proxy Manager反代

### ISSUE THREAD

**Issue by nobodypengium** [ledccn/iyuuplus-dev#68]
参照[https://doc.iyuu.cn/guide/qa-others#proxy](文档中其他相关问答部分)设置了反代参数
![image](https://github.com/ledccn/iyuuplus-dev/assets/13833330/e1ff94b5-cf1a-4c51-8fdf-3235943ab4a6)
```
location / {
 proxy_pass http://x.x.x.x:2911/; 
 proxy_set_header Host $http_host;
 proxy_redirect http:// https://; 

 proxy_set_header X-Forwarded-Host $http_host; 
 proxy_set_header X-Forwarded-Port $server_port; 
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_set_header X-Forwarded-Scheme $scheme;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $remote_addr;

 
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 proxy_http_version 1.1;
 
}
```

```
 proxy_set_header Connection "upgrade";
```
这一行为何不用文档中的
```
proxy_set_header Connection $connection_upgrade;
```
如果用文档中的```proxy_set_header Connection $connection_upgrade;```会变offline，我看最新NPM似乎修过一个与```$connection_upgrade;```有关的[bug](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3474)，不过没看明白

不知道是否有人成功使用Nginx Proxy Manager代理了iyuu的websocket，希望有大佬分享下经验，如果不行我就换个lucky吧，技术力不足（逃

**Comment by yourvid** [comment]
现在只需要一个8780端口了，软件内部自动反代了web端口和长连接端口。进入web页面自己修改默认长连接端口为8780

**Comment by nobodypengium** [comment]
> 现在只需要一个8780端口了，软件内部自动反代了web端口和长连接端口。进入web页面自己修改默认长连接端口为8780 ![image](https://private-user-images.githubusercontent.com/33681727/339096631-11de419a-1fc4-4ff7-8654-71c7b690473c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTE2NzUsIm5iZiI6MTcxODI1MTM3NSwicGF0aCI6Ii8zMzY4MTcyNy8zMzkwOTY2MzEtMTFkZTQxOWEtMWZjNC00ZmY3LTg2NTQtNzFjN2I2OTA0NzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA0MDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OTUyNTQwZDc4ZjhhOGRlZjhlY2I3ZDZkODY3ODNkYmQwOTA0YjFjYWQ2YWFmNGZmMDBhZWQ2MTliNjQ3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jXmP_gQ-dww6WxOYh6UjsRq3uCSeCZddReH4p5QDAPQ) ![image](https://private-user-images.githubusercontent.com/33681727/339096864-ef76d031-0cc4-49fb-a71d-73e2ceef7368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTE2NzUsIm5iZiI6MTcxODI1MTM3NSwicGF0aCI6Ii8zMzY4MTcyNy8zMzkwOTY4NjQtZWY3NmQwMzEtMGNjNC00OWZiLWE3MWQtNzNlMmNlZWY3MzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA0MDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzk2NjBiYTM3MjZhNWZlN2JiNTg2ZjAwZDA0OWRmZTkyMGM2NzgxOTg2YjNiNzJjYjY2ZTY2ZTk3NGFmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5p3vTf3n0dmDlrY2ZoViGjcnK9ge37IeN8cppSrzpw0)

感谢大佬回答，我这里已经调好了，具体配置如下：
**Unraid docker 配置端口转发**
2911可以是任意你喜欢的端口，我也不知道当时为啥要设置这个端口了
![image](https://github.com/ledccn/iyuuplus-dev/assets/13833330/1ad9f2e4-644e-4158-9b0d-1bcd7789236e)
**Nginx Proxy Manager**
![image](https://github.com/ledccn/iyuuplus-dev/assets/13833330/79d65c51-e226-483c-9f91-0334170cd280)
**路由器通信端口转发**
12345端口转发到Nginx Proxy Manager的宿主机
**重点：iyuu长连接端口配置**
跟你实际访问页面的端口一样！
![image](https://github.com/ledccn/iyuuplus-dev/assets/13833330/d04cec93-ebfe-4c8b-9656-7ba17c7d3af6)
