### ISSUE TITLE
无法查看日志

### ISSUE THREAD

**Issue by Rick630** [ledccn/iyuuplus-dev#7]
计划任务添加后手动执行了几次，点击日志图标打开页面无法查看日志

![WX20240424-134214@2x](https://github.com/ledccn/iyuuplus-dev/assets/11673596/49614f72-93d2-451f-a7ab-41553c99e6e9)

在任务菜单里也无法查看到具体日志
![WX20240424-134246@2x](https://github.com/ledccn/iyuuplus-dev/assets/11673596/ad03c3c9-d6f7-4998-a4d7-43f07467fc9c)

**Comment by ledccn** [comment]
首次进入后台，需要重启应用；如果docker安装的 重启容器即可。
