### ISSUE TITLE
辅种计划任务无法正常运行：请求缺少 token

### ISSUE THREAD

**Issue by dreamerblue** [ledccn/iyuuplus-dev#71]
docker 安装，已配置 tr 下载器和站点（两个支持列表中的手动填写站点，非合作站点），新建计划任务并执行后，查看日志报错 `请求缺少token`。IYUU token 在初始化时已经填写，这个 token 指的是什么？如何进一步排查呢？

仪表盘上做种数可以正常拉取，辅种无数据。

```plain
2024-06-16 19:28:22即将执行自动辅种，任务id：1
请求缺少token
 当前时间：2024-06-16 19:28:22
 IYUU版本：8.2.30
 Docker：是
 操作系统：Linux
 运行环境：Linux
 PHP二进制路径：/usr/bin/php83
 PHP版本号：8.3.8
辅种完毕，感谢使用IYUU自动辅种！
```

<img width="1494" alt="image" src="https://github.com/ledccn/iyuuplus-dev/assets/19774268/f599c120-41b4-4ee8-a36a-f64db22d7afc">

**Comment by snowwalk** [comment]
之前出过同样的问题。
后边没管他，重新更新了一版，覆盖安装，绑定合作站点，然后恢复正常了。

**Comment by dreamerblue** [comment]
@ledccn 晕，浪费很多时间搜索排查和翻阅源码。最后摸索出的解决方法竟然是需要绑定一个合作站点才能激活辅种功能，太黑盒了吧。这么重要的步骤为什么不写在文档里？

**Comment by yurihuruitao** [comment]
没有合作站点怎么办？
