### ISSUE TITLE
[hdcity]辅种下载种子失败（实际返回302）

### ISSUE THREAD

**Issue by snowwalk** [ledccn/iyuuplus-dev#72]
hdcity 域名：https://hdcity.city。
能够拉取辅种列表，但在辅种下载种子时，服务端返回302。iyuu判定cookie过期。但实际是下载种子时，服务端返回302，重定向到了一个新的URL，这个新的URL是可以正常下载种子的。

下面是返回的信息。location中的链接已经脱敏替换

`请求错误：error_message为空:[302,["HTTP\/1.1 200 Connection established","HTTP\/2 302 ","date: Mon, 17 Jun 2024 08:10:51 GMT","content-type: text\/html; charset=UTF-8","location: \/\/hctres.leniter.org\/dl.php?k=xxxxx&t=44865","cf-cache-status: DYNAMIC","report-to: {\"endpoints\":[{\"url\":\"https:\\\/\\\/a.nel.cloudflare.com\\\/report\\\/v4?s=Z4oLGTDeE2ZUjMcL9yfUeI3vIhxik9k6tyF4%2Bxu13N62vzVzlNszmGilNuvplffFUm%2F%2FnxVNOKx3vUVIsG8RiD0Dkud%2BG2feNb6Sq5hBsUgr3agf0zboo8XjL4JFAQ%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}","nel: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}","strict-transport-security: max-age=2592000; includeSubDomains; preload","server: cloudflare","cf-ray: 895190c159bc5df5-HKG","alt-svc: h3=\":443\"; ma=86400"],""] Cookie过期`

**Comment by ledccn** [comment]
已修复 v8.2.33
