### ISSUE TITLE
几点体验优化的建议

### ISSUE THREAD

**Issue by cng10001** [ledccn/iyuuplus-dev#78]
**1，站点添加：点击导入旧版配置后，希望能很快筛选到添加的站点**
现在我导入的这些站点一个都不在首页，我得一个个去翻找站，再点启用。希望导入的站点优先展示在第一页。
![站点添加~](https://github.com/ledccn/iyuuplus-dev/assets/115156545/bb5e7e9d-87ee-454d-b8d0-a93ebcb1cc01)

**2，“刷新辅种”命名。**
小看了这个绿色标识，一开始以为点刷新后会更新辅种的状态这个表面意思。当然实际上面有说明，希望能给个更直接准确的名字，可以就叫‘重试失败的种子’
![image](https://github.com/ledccn/iyuuplus-dev/assets/115156545/2907735b-7a43-4997-8358-06b1d318a124)

**3，自动辅种页面，站点查询筛选**
目前查询站点要么是一个个下拉翻找，要么是手输，如果把配置的站点优先展示在上方会方便很多。
![手输](https://github.com/ledccn/iyuuplus-dev/assets/115156545/29267581-00d4-487b-80f4-9e45549c363f)

**4，任务管理，自定义执行表达式。**
希望后续能支持自定义。
![image](https://github.com/ledccn/iyuuplus-dev/assets/115156545/41af8737-34c1-4c80-a261-cf6d523d6047)

**Comment by ledccn** [comment]
1. 需求已记录，待实现；
2. 已实现
3. 暂时先这样吧
4. 需求已记录，待实现；

**Comment by cng10001** [comment]
![image](https://github.com/ledccn/iyuuplus-dev/assets/115156545/ccc204a6-9f2d-41cf-9126-87c8c1ad671e)
大佬 再请教一下，这个描述是什么意思，
这2条下载器里并没有添加到，但是显示成功了。

**Comment by ledccn** [comment]
添加进下载器的是错误的种子信息。
