### ISSUE TITLE
大佬你好，麻烦看到后联系一下我，并删除该帖子

### ISSUE THREAD

**Issue by Kris-haidan** [ledccn/iyuuplus-dev#79]
IYUU大佬你好，我是海胆站的站长，我很喜欢你的这个产品，由于我们站点种子结构改动太大，无法适配大多种子，现我站已经制作了接口，希望能和你对接一下，并且想向你申请一下成为验证站点，麻烦有看到加我TG一下@haidanpt

**Comment by ledccn** [comment]
可以的，但是我没用过TG。我QQ是367013672。




大卫
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ledccn/iyuuplus-dev"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 晚上10:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ledccn/iyuuplus-dev] 大佬你好，麻烦看到后联系一下我，并删除该帖子 (Issue #79)





 
***@***.***
