### ISSUE TITLE
Transmission无法使用空用户名密码

### ISSUE THREAD

**Issue by ShawsonBian** [ledccn/iyuuplus-dev#8]
添加下载器时，选择Transmission，用户名密码不能为空，但tr本身是允许无用户名密码的，很多第三方工具也都允许，能否去掉tr用户名密码的强校验？

**Comment by ledccn** [comment]
可以的。这个得测试一下，你群里联系我。我改一版发给你。

**Comment by ShawsonBian** [comment]
晚点我加q群那，目前只在tg群里

从 Windows 版邮件发送

发件人: David
发送时间: 2024年4月25日 9:27
收件人: ledccn/iyuuplus-dev
抄送: ShawsonBian; Author
主题: Re: [ledccn/iyuuplus-dev] Transmission无法使用空用户名密码 (Issue #8)

可以的。这个得测试一下，你群里联系我。我改一版发给你。

**Comment by chux1995** [comment]
这个解决了吗？现在这一版还是必填项

**Comment by ShawsonBian** [comment]
> 这个解决了吗？现在这一版还是必填项

解决了 填写null即可
