### ISSUE TITLE
docker运行报错：Could not open input file: /iyuu/start.php

### ISSUE THREAD

**Issue by lemon66789** [ledccn/iyuuplus-dev#81]
![Uploading QQ截图20240701232518.png…]()
历史问题中有人问过这个问题，解答是拉取代码失败，重启容器，但我重启N次后该问题依然存在

**Comment by lemon66789** [comment]
补充：已确认文件夹权限，data及iyuu均为everyone完全控制

**Comment by qq2519157** [comment]
请问下你是如何解决的？

**Comment by lemon66789** [comment]
> 请问下你是如何解决的？
网络问题，排查自己的docker网络，关闭代理、检查容器内是否能访问外网、检查容器网络设置
