### ISSUE TITLE
MP插件自动辅种馒头失败

### ISSUE THREAD

**Issue by shawn0090** [ledccn/iyuuplus-dev#84]
用MP里面的IYUU自动辅种插件，一直提示获取种子下载链接失败，插件版本V1.9
![image](https://github.com/ledccn/iyuuplus-dev/assets/172612019/f96a152a-cfde-490b-b9e5-da4307142418)

![image](https://github.com/ledccn/iyuuplus-dev/assets/172612019/4f263f76-e2f3-4ad9-97c0-bb9b2ac13df8)

**Comment by leichaoL** [comment]
我直接用的iyuu没用过mp，解决方案供你参考，配置站点里的镜像域名为馒头给的api域名。

**Comment by Devinaille** [comment]
通过测试发现，iyuu接口`App.Api.Sites`返回的结果如下(隐藏了部分站点要求隐藏的数据）
```json
{
    "ret": 200,
    "data": {
        "sites": [
            {
                "id": 3,
                "base_url": "api.xxx.cc",
                "download_page": "api/torrent/genDlToken",
                "details_page": "detail/{}",
                "is_https": 2,
                "cookie_required": 0
            }
        ]
    }
}
```
可以发现download_page下载路径没有可以替换的变量，看api文档是需要传一个id，感觉是这个问题

**Comment by lindaiyu99** [comment]
> 我直接用的iyuu没用过mp，解决方案供你参考，配置站点里的镜像域名为馒头给的api域名。

感谢分享，这个对我有帮助，早上找了很久辅种错误的原因。现在正常了。

**Comment by eaglexxxm** [comment]
> > 我直接用的iyuu没用过mp，解决方案供你参考，配置站点里的镜像域名为馒头给的api域名。
> 
> 感谢分享，这个对我有帮助，早上找了很久辅种错误的原因。现在正常了。
> 
> 未修正之前，IYUU辅种提示“1.准备下载种子 请求错误：HTTP/2 403”，改过站点的镜像域名就正常了，供参考。

用了哪个api域名？改了直接是连不上啊。

**Comment by leichaoL** [comment]
> > > 我直接用的iyuu没用过mp，解决方案供你参考，配置站点里的镜像域名为馒头给的api域名。
> > 
> > 
> > 感谢分享，这个对我有帮助，早上找了很久辅种错误的原因。现在正常了。
> > 未修正之前，IYUU辅种提示“1.准备下载种子 请求错误：HTTP/2 403”，改过站点的镜像域名就正常了，供参考。
> 
> 用了哪个api域名？改了直接是连不上啊。

馒头首页通知处有，自行查看**api調用域名方式更改通知** (3 個月)。但我不确定现在这种方式能否行得通，按理来说iyuu应该早就把新域名加进去了。
