### ISSUE TITLE
每日辅种数量限制没有生效

### ISSUE THREAD

**Issue by gyf9835** [ledccn/iyuuplus-dev#93]
添加了一个新的站点，辅种数量默认20个/天，在计划任务中运行了一次新站点的辅种。在【自动辅种】页面看到待辅种250+条，之后看到iyuu页面右上角一直提示绿色的种子添加成功消息，至少添加了80个新种子，没有停的意思。尝试docker重启后还会继续辅种。

**Comment by gyf9835** [comment]
可能这个bug和站点有关，刚才添加的新站点发现辅种数量限制生效了，生效的站点是铂金家，上面提到有问题的站点是人人人

**Comment by ledccn** [comment]
旧数据导入之后，需要点击编辑，再保存，才会真正落库。

**Comment by hironwu** [comment]
> 同样来报一个 今天添加了高清杜比站，手动运行自动辅种任务一次，发现所有的待辅种几百个都会尝试去下载种子，导致超过了站点每小时允许的最大数60。站点设置中配置的20个限额无效。
> 
> 期盼大大能修复。

我也同样出现这个问题，也是杜比站，设定的20，结果全超过限制，四小时不能下载种子，很烦。
