### ISSUE TITLE
最新版本报错 今天更新最新的docker

### ISSUE THREAD

**Issue by 907739769** [ledccn/iyuuplus-dev#94]
worker[plugin.cron.scheduler:249] exit with status 64000
PDOException: SQLSTATE[HY000] [2002] No such file or directory in /iyuu/vendor/illuminate/database/Connectors/Connector.php:65
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connectors/Connector.php(65): PDO->__construct()
#1 /iyuu/vendor/illuminate/database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /iyuu/vendor/illuminate/database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /iyuu/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#4 /iyuu/vendor/illuminate/database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#6 /iyuu/vendor/illuminate/database/Connection.php(1339): call_user_func()
#7 /iyuu/vendor/illuminate/database/Connection.php(1375): Illuminate\Database\Connection->getPdo()
#8 /iyuu/vendor/illuminate/database/Connection.php(528): Illuminate\Database\Connection->getReadPdo()
#9 /iyuu/vendor/illuminate/database/Connection.php(423): Illuminate\Database\Connection->getPdoForSelect()
#10 /iyuu/vendor/illuminate/database/Connection.php(816): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#11 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#12 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#13 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#14 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#15 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#16 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#17 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#18 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#19 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#20 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#21 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#22 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#23 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#24 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#25 /iyuu/support/helpers.php(470): worker_bind()
#26 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#27 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#28 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#29 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#30 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#31 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#32 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#33 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#34 /iyuu/start.php(4): support\App::run()
#35 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] No such file or directory (Connection: plugin.admin.mysql, SQL: select * from `cn_crontab` where `enabled` = 1 order by `sort` desc) in /iyuu/vendor/illuminate/database/Connection.php:829
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#1 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#2 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#3 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#4 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#5 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#6 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#9 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#10 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#11 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#12 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#13 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#14 /iyuu/support/helpers.php(470): worker_bind()
#15 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#16 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#17 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#18 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#19 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#20 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#21 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#22 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#23 /iyuu/start.php(4): support\App::run()
#24 {main}
worker[plugin.cron.scheduler:251] exit with status 64000
PDOException: SQLSTATE[HY000] [2002] No such file or directory in /iyuu/vendor/illuminate/database/Connectors/Connector.php:65
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connectors/Connector.php(65): PDO->__construct()
#1 /iyuu/vendor/illuminate/database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /iyuu/vendor/illuminate/database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /iyuu/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#4 /iyuu/vendor/illuminate/database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#6 /iyuu/vendor/illuminate/database/Connection.php(1339): call_user_func()
#7 /iyuu/vendor/illuminate/database/Connection.php(1375): Illuminate\Database\Connection->getPdo()
#8 /iyuu/vendor/illuminate/database/Connection.php(528): Illuminate\Database\Connection->getReadPdo()
#9 /iyuu/vendor/illuminate/database/Connection.php(423): Illuminate\Database\Connection->getPdoForSelect()
#10 /iyuu/vendor/illuminate/database/Connection.php(816): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#11 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#12 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#13 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#14 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#15 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#16 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#17 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#18 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#19 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#20 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#21 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#22 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#23 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#24 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#25 /iyuu/support/helpers.php(470): worker_bind()
#26 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#27 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#28 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#29 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#30 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#31 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#32 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#33 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#34 /iyuu/start.php(4): support\App::run()
#35 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] No such file or directory (Connection: plugin.admin.mysql, SQL: select * from `cn_crontab` where `enabled` = 1 order by `sort` desc) in /iyuu/vendor/illuminate/database/Connection.php:829
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#1 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#2 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#3 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#4 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#5 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#6 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#9 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#10 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#11 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#12 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#13 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#14 /iyuu/support/helpers.php(470): worker_bind()
#15 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#16 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#17 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#18 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#19 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#20 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#21 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#22 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#23 /iyuu/start.php(4): support\App::run()
#24 {main}
worker[plugin.cron.scheduler:253] exit with status 64000
PDOException: SQLSTATE[HY000] [2002] No such file or directory in /iyuu/vendor/illuminate/database/Connectors/Connector.php:65
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connectors/Connector.php(65): PDO->__construct()
#1 /iyuu/vendor/illuminate/database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /iyuu/vendor/illuminate/database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /iyuu/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#4 /iyuu/vendor/illuminate/database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#6 /iyuu/vendor/illuminate/database/Connection.php(1339): call_user_func()
#7 /iyuu/vendor/illuminate/database/Connection.php(1375): Illuminate\Database\Connection->getPdo()
#8 /iyuu/vendor/illuminate/database/Connection.php(528): Illuminate\Database\Connection->getReadPdo()
#9 /iyuu/vendor/illuminate/database/Connection.php(423): Illuminate\Database\Connection->getPdoForSelect()
#10 /iyuu/vendor/illuminate/database/Connection.php(816): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#11 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#12 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#13 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#14 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#15 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#16 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#17 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#18 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#19 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#20 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#21 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#22 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#23 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#24 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#25 /iyuu/support/helpers.php(470): worker_bind()
#26 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#27 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#28 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#29 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#30 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#31 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#32 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#33 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#34 /iyuu/start.php(4): support\App::run()
#35 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] No such file or directory (Connection: plugin.admin.mysql, SQL: select * from `cn_crontab` where `enabled` = 1 order by `sort` desc) in /iyuu/vendor/illuminate/database/Connection.php:829
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#1 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#2 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#3 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#4 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#5 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#6 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#9 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#10 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#11 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#12 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#13 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#14 /iyuu/support/helpers.php(470): worker_bind()
#15 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#16 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#17 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#18 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#19 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#20 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#21 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#22 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#23 /iyuu/start.php(4): support\App::run()
#24 {main}
worker[plugin.cron.scheduler:259] exit with status 64000
PDOException: SQLSTATE[HY000] [2002] No such file or directory in /iyuu/vendor/illuminate/database/Connectors/Connector.php:65
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connectors/Connector.php(65): PDO->__construct()
#1 /iyuu/vendor/illuminate/database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /iyuu/vendor/illuminate/database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /iyuu/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#4 /iyuu/vendor/illuminate/database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#6 /iyuu/vendor/illuminate/database/Connection.php(1339): call_user_func()
#7 /iyuu/vendor/illuminate/database/Connection.php(1375): Illuminate\Database\Connection->getPdo()
#8 /iyuu/vendor/illuminate/database/Connection.php(528): Illuminate\Database\Connection->getReadPdo()
#9 /iyuu/vendor/illuminate/database/Connection.php(423): Illuminate\Database\Connection->getPdoForSelect()
#10 /iyuu/vendor/illuminate/database/Connection.php(816): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#11 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#12 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#13 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#14 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#15 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#16 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#17 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#18 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#19 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#20 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#21 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#22 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#23 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#24 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#25 /iyuu/support/helpers.php(470): worker_bind()
#26 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#27 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#28 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#29 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#30 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#31 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#32 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#33 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#34 /iyuu/start.php(4): support\App::run()
#35 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] No such file or directory (Connection: plugin.admin.mysql, SQL: select * from `cn_crontab` where `enabled` = 1 order by `sort` desc) in /iyuu/vendor/illuminate/database/Connection.php:829
Stack trace:
#0 /iyuu/vendor/illuminate/database/Connection.php(983): Illuminate\Database\Connection->runQueryCallback()
#1 /iyuu/vendor/illuminate/database/Connection.php(962): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection()
#2 /iyuu/vendor/illuminate/database/Connection.php(785): Illuminate\Database\Connection->handleQueryException()
#3 /iyuu/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->run()
#4 /iyuu/vendor/illuminate/database/Query/Builder.php(2871): Illuminate\Database\Connection->select()
#5 /iyuu/vendor/illuminate/database/Query/Builder.php(2860): Illuminate\Database\Query\Builder->runSelect()
#6 /iyuu/vendor/illuminate/database/Query/Builder.php(3414): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /iyuu/vendor/illuminate/database/Query/Builder.php(2859): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(738): Illuminate\Database\Query\Builder->get()
#9 /iyuu/vendor/illuminate/database/Eloquent/Builder.php(722): Illuminate\Database\Eloquent\Builder->getModels()
#10 /iyuu/plugin/cron/app/model/Crontab.php(73): Illuminate\Database\Eloquent\Builder->get()
#11 /iyuu/plugin/cron/process/SchedulerProcess.php(149): plugin\cron\app\model\Crontab::allEnabledCrontab()
#12 /iyuu/plugin/cron/process/SchedulerProcess.php(140): plugin\cron\process\SchedulerProcess->initPoolsCrontab()
#13 /iyuu/support/helpers.php(432): plugin\cron\process\SchedulerProcess->onWorkerStart()
#14 /iyuu/support/helpers.php(470): worker_bind()
#15 /iyuu/vendor/workerman/workerman/Worker.php(2497): {closure}()
#16 /iyuu/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#17 /iyuu/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#18 /iyuu/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#19 /iyuu/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#20 /iyuu/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#21 /iyuu/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#22 /iyuu/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#23 /iyuu/start.php(4): support\App::run()
#24 {main}
worker[plugin.cron.scheduler:261] exit with status 64000
Success 载入计划任务，ID 1 | 标题：自动转移
Success 载入计划任务，ID 2 | 标题：自动辅种

**Comment by 907739769** [comment]
![image](https://github.com/user-attachments/assets/c44064b3-5723-43d5-9ff4-507ef44a596c)

**Comment by 907739769** [comment]
![image](https://github.com/user-attachments/assets/ff0840ac-8740-418d-ab4f-353c46ab72d4)

**Comment by 907739769** [comment]
群晖设置root权限解决了

**Comment by zxyxyxx** [comment]
可以详细说一下怎么解决的吗，我也遇到了

**Comment by xylplm** [comment]
同样的报错，什么原因？
