### ISSUE TITLE
新功能建议：推送种子时自动设置 “单种上传限速”

### ISSUE THREAD

**Issue by hui-shao** [ledccn/iyuuplus-dev#98]
### 原因
辅种后，种子的上传速度默认没有限制，具有较大上行宽带的用户有可能造成超速，引发封禁。因此，希望 IYUU 在推送种子之时即设置好单种限速，以绝后顾之忧。

### 其他建议
单种限速的配置框，个人感觉可以放进“站点配置”中。

### 分享
自己写了个根据 tracker 设置种子限速的工具，有需要的同志自取：https://github.com/hui-shao/qbit_speed_limit_per_tracker
注：虽然小工具能设置单种限速，但“辅种完成”和“工具运行”之间仍存在不安全的空窗期，因此还是希望 IYUU 在添加种子时就能支持限速设置。

**Comment by ledccn** [comment]
感谢建议，后续增加

**Comment by mangzhu** [comment]
请问这个功能添加了么？
